### ISSUE TITLE
Compile causes libpng error

### ISSUE THREAD

**Issue by garethmcc** [ZeroSharp/serverless-php#10]
Hello there. I was trying to recompile the PHP binary with the `--enable-dom` flag and after it completed trying to execute the binary on my local machine or on a lambda resulted in the error:

`php: error while loading shared libraries: libpng15.so.15: cannot open shared object file: No such file or directory`

Wondering if there was something I was missing?

**Comment by jcoby** [comment]
I ran into this as well and had to change the FROM line in the dockerfile to read:

`FROM amazonlinux:2017.03.1.20170812`

The newer version of Amazon Linux available through docker doesn't match the Lambda runtime.

**Comment by shamp00** [comment]
Nice find and thanks for responding! I've updated the docker file and added a comment to it to check which version is currently supported [here](https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html).
