### ISSUE TITLE
Invoke is failing with issue in AWS Lambda - Process exited before completing request 

### ISSUE THREAD

**Issue by appsassociates-dev** [ZeroSharp/serverless-php#4]
![image](https://user-images.githubusercontent.com/28426910/27536892-c8d1ca64-5a8e-11e7-8172-885315dab800.png)

**Comment by shamp00** [comment]
Not sure why, but your `hello` function is taking too long. Try adding `timeout:  15` to the serverless.yml (section `provider`).
