### ISSUE TITLE
"/lib64/libcrypto.so.10: version `OPENSSL_1.0.2' not found (required by ./php)" error occurs after PHP binary is rebuilt

### ISSUE THREAD

**Issue by JakubBarta** [ZeroSharp/serverless-php#8]
When I install this project and deploy it right away, everything works. 
But after I rebuild PHP binary by running `sh buildphp.sh` (without modifying anything) and then deploy, execution always fails with "/lib64/libcrypto.so.10: version `OPENSSL_1.0.2' not found (required by ./php)" error.

**Comment by dprevite** [comment]
Having the same issue here, looks like Amazon Linux 2017.09 ships with OpenSSL 1.0.2 but Lambda is still on 1.0.1.

**Comment by shamp00** [comment]
I think I got it working. Thanks @dprevite for isolating the problem. The buildphp.sh now installs OpenSSH 1.0.1k. When Amazon updates the lambda image to 1.0.2 we can revert to using yum.
